language: haskell
sudo: required
dist: trusty
before_install: 
  - cabal update
  - travis/install-imagemagick.sh
  - travis/cabal-apt-install --only-dependencies --force-reinstalls
  - travis/cabal-apt-install test-framework test-framework-hunit test-framework-quickcheck2  --force-reinstalls
install:
  - cabal configure --enable-tests -fBuildExamples
  - cabal build
test:
  - cabal test --show-details=always
